CREATE DATABASE IF NOT EXISTS pedido_service;
CREATE DATABASE IF NOT EXISTS stock_service;
CREATE DATABASE IF NOT EXISTS pago_service;
CREATE DATABASE IF NOT EXISTS email_service;
CREATE DATABASE IF NOT EXISTS factura_service;
